# -----------------------------------------------------------------------------
# @author    STM32Cube bundle system
# -----------------------------------------------------------------------------
# @attention
#
# Copyright (c) 2025 STMicroelectronics.
# All rights reserved.
#
# This software is licensed under terms that can be found in the LICENSE file
# in the root directory of this software component.
# If no LICENSE file comes with this software, it is provided AS-IS.
#
# -----------------------------------------------------------------------------

# This file describes GNU Tools for STM32 Toolchain.
#
#   - Applies to toolchain: GNU Tools for STM32 Toolchain 13.3.1 and greater

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Defaults used by NCU Simulink/Embedded Coder flow (can be overridden by -D).
if(NOT DEFINED CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMAKE_EXPORT_COMPILE_COMMANDS)
  set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "" FORCE)
endif()
if(NOT DEFINED CMSIS_Dvendor)
  set(CMSIS_Dvendor "STMicroelectronics:13" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Dname)
  set(CMSIS_Dname "STM32H755ZIT6" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Dcore)
  set(CMSIS_Dcore "Cortex-M7" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Dtz)
  set(CMSIS_Dtz "NO_TZ" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Dfpu)
  set(CMSIS_Dfpu "DP_FPU" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Ddsp)
  set(CMSIS_Ddsp "DSP" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Dmve)
  set(CMSIS_Dmve "NO_MVE" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Dmpu)
  set(CMSIS_Dmpu "MPU" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Dendian)
  set(CMSIS_Dendian "Little-endian" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Dsecure)
  set(CMSIS_Dsecure "" CACHE STRING "" FORCE)
endif()
if(NOT DEFINED CMSIS_Tcompiler)
  set(CMSIS_Tcompiler "GCC" CACHE STRING "" FORCE)
endif()

# Some target device related default GCC settings
if(CMSIS_Dcore STREQUAL "Cortex-M0")
  set(CPU_FLAGS -mcpu=cortex-m0)
elseif(CMSIS_Dcore STREQUAL "Cortex-M0+")
  set(CPU_FLAGS -mcpu=cortex-m0plus)
elseif(CMSIS_Dcore STREQUAL "Cortex-M1")
  set(CPU_FLAGS -mcpu=cortex-m1)
elseif(CMSIS_Dcore STREQUAL "Cortex-M3")
  set(CPU_FLAGS -mcpu=cortex-m3)
elseif(CMSIS_Dcore STREQUAL "Cortex-M4")
  if(CMSIS_Dfpu STREQUAL "SP_FPU")
    set(CPU_FLAGS -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard)
  else()
    set(CPU_FLAGS -mcpu=cortex-m4)
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M7")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CPU_FLAGS -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard)
  elseif(CMSIS_Dfpu STREQUAL "SP_FPU")
    set(CPU_FLAGS -mcpu=cortex-m7 -mfpu=fpv5-sp-d16 -mfloat-abi=hard)
  else()
    set(CPU_FLAGS -mcpu=cortex-m7)
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M23")
  set(CPU_FLAGS -mcpu=cortex-m23)
elseif(CMSIS_Dcore STREQUAL "Cortex-M33")
  if(CMSIS_Dfpu STREQUAL "SP_FPU")
    if(CMSIS_Ddsp STREQUAL "DSP")
      set(CPU_FLAGS -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard)
    else()
      set(CPU_FLAGS -mcpu=cortex-m33+nodsp -mfpu=fpv5-sp-d16 -mfloat-abi=hard)
    endif()
  else()
    if(CMSIS_Ddsp STREQUAL "DSP")
      set(CPU_FLAGS -mcpu=cortex-m33)
    else()
      set(CPU_FLAGS -mcpu=cortex-m33+nodsp)
    endif()
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M35P")
  if(CMSIS_Dfpu STREQUAL "SP_FPU")
    if(CMSIS_Ddsp STREQUAL "DSP")
      set(CPU_FLAGS -mcpu=cortex-m35p -mfpu=fpv5-sp-d16 -mfloat-abi=hard)
    else()
      set(CPU_FLAGS -mcpu=cortex-m35p+nodsp -mfpu=fpv5-sp-d16 -mfloat-abi=hard)
    endif()
  else()
    if(CMSIS_Ddsp STREQUAL "DSP")
      set(CPU_FLAGS -mcpu=cortex-m35p)
    else()
      set(CPU_FLAGS -mcpu=cortex-m35p+nodsp)
    endif()
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M55")
  if(CMSIS_Dfpu STREQUAL "NO_FPU")
    if(CMSIS_Dmve STREQUAL "NO_MVE")
      set(CPU_FLAGS -mcpu=cortex-m55+nofp+nomve)
    else()
      set(CPU_FLAGS -mcpu=cortex-m55+nofp)
    endif()
  else()
    if(CMSIS_Dmve STREQUAL "NO_MVE")
      set(CPU_FLAGS -mcpu=cortex-m55+nomve -mfloat-abi=hard)
    elseif(CMSIS_Dmve STREQUAL "MVE")
      set(CPU_FLAGS -mcpu=cortex-m55+nomve.fp -mfloat-abi=hard)
    else()
      set(CPU_FLAGS -mcpu=cortex-m55 -mfloat-abi=hard)
    endif()
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M85")
  if(CMSIS_Dfpu STREQUAL "NO_FPU")
    if(CMSIS_Dmve STREQUAL "NO_MVE")
      set(CPU_FLAGS -mcpu=cortex-m85+nofp+nomve)
    else()
      set(CPU_FLAGS -mcpu=cortex-m85+nofp)
    endif()
  else()
    if(CMSIS_Dmve STREQUAL "NO_MVE")
      set(CPU_FLAGS -mcpu=cortex-m85+nomve -mfloat-abi=hard)
    elseif(CMSIS_Dmve STREQUAL "MVE")
      set(CPU_FLAGS -mcpu=cortex-m85+nomve.fp -mfloat-abi=hard)
    else()
      set(CPU_FLAGS -mcpu=cortex-m85 -mfloat-abi=hard)
    endif()
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A5")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CPU_FLAGS -mcpu=cortex-a5+nosimd -mfpu=auto -mfloat-abi=hard)
  else()
    set(CPU_FLAGS -mcpu=cortex-a5+nosimd+nofp)
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A7")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CPU_FLAGS -mcpu=cortex-a7+nosimd -mfpu=auto -mfloat-abi=hard)
  else()
    set(CPU_FLAGS -mcpu=Cortex-a7+nosimd+nofp)
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A9")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CPU_FLAGS -mcpu=cortex-a9+nosimd -mfpu=auto -mfloat-abi=hard)
  else()
    set(CPU_FLAGS -mcpu=cortex-a9+nosimd+nofp)
  endif()
endif()

if(CMSIS_Dendian STREQUAL "Little-endian")
  set(CPU_FLAGS ${CPU_FLAGS} -mlittle-endian)
elseif(CMSIS_Dendian STREQUAL "Big-endian")
  set(CPU_FLAGS ${CPU_FLAGS} -mbig-endian)
endif()

set(CPU_FLAGS ${CPU_FLAGS} -mthumb)

# Some C Pre-Processor related default GCC settings 
if(CMSIS_Dsecure STREQUAL "Secure" OR CMSIS_Dsecure STREQUAL "Secure-only")
  set(SECURE_FLAGS "-mcmse")
endif()

# Some default GCC settings
# Prefer explicit compiler paths so Simulink toolchain validation does not
# depend on the caller PATH contents.
set(TOOLCHAIN_PREFIX arm-none-eabi-)

# Optional override:
#   -DARM_GCC_BIN_DIR="C:/path/to/bin"
set(_ARM_GCC_HINTS "")
if(DEFINED ARM_GCC_BIN_DIR AND EXISTS "${ARM_GCC_BIN_DIR}")
  list(APPEND _ARM_GCC_HINTS "${ARM_GCC_BIN_DIR}")
endif()
if(DEFINED ENV{ARM_GCC_BIN_DIR} AND EXISTS "$ENV{ARM_GCC_BIN_DIR}")
  list(APPEND _ARM_GCC_HINTS "$ENV{ARM_GCC_BIN_DIR}")
endif()

# Common STM32CubeIDE GNU Tools for STM32 install locations (Windows).
file(GLOB _STM32_GCC_GLOB
  "C:/ST/STM32CubeIDE_*/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.*/tools/bin"
  "C:/Program Files/STMicroelectronics/STM32Cube/STM32CubeIDE_*/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.*/tools/bin")
if(_STM32_GCC_GLOB)
  list(APPEND _ARM_GCC_HINTS ${_STM32_GCC_GLOB})
endif()
set(FLAGS                           "-fdata-sections -ffunction-sections -Wl,--gc-sections -Wno-comment")
set(CPP_FLAGS                       "${FLAGS} -fno-rtti -fno-exceptions -fno-threadsafe-statics")

set(CMAKE_C_FLAGS                   ${FLAGS})
set(CMAKE_CXX_FLAGS                 ${CPP_FLAGS})

find_program(_ARM_GCC   NAMES arm-none-eabi-gcc   HINTS ${_ARM_GCC_HINTS})
find_program(_ARM_GXX   NAMES arm-none-eabi-g++   HINTS ${_ARM_GCC_HINTS})
find_program(_ARM_OBJCOPY NAMES arm-none-eabi-objcopy HINTS ${_ARM_GCC_HINTS})
find_program(_ARM_SIZE  NAMES arm-none-eabi-size  HINTS ${_ARM_GCC_HINTS})

if(_ARM_GCC)
  set(CMAKE_C_COMPILER ${_ARM_GCC})
else()
  set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
endif()
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})

if(_ARM_GXX)
  set(CMAKE_CXX_COMPILER ${_ARM_GXX})
else()
  set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)
endif()

if(_ARM_OBJCOPY)
  set(CMAKE_OBJCOPY ${_ARM_OBJCOPY})
else()
  set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy)
endif()

if(_ARM_SIZE)
  set(CMAKE_SIZE ${_ARM_SIZE})
else()
  set(CMAKE_SIZE ${TOOLCHAIN_PREFIX}size)
endif()

set(CMAKE_EXECUTABLE_SUFFIX_ASM     ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C       ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_CXX     ".elf")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

include_directories(${CMAKE_CURRENT_LIST_DIR}/include)