/***************************************************************
**
** NCU Source File
**
** File         :  http_custom_fs.c
** Module       :  eth
** Author       :  SH
** Created      :  2026-03-28 (YYYY-MM-DD)
** License      :  MIT
** Description  :  lwIP HTTPD custom file mapping for embedded web assets
**
***************************************************************/

#include <lwip/apps/fs.h>

#include <string.h>

/* Symbols generated by embed_resources() in m7/CMakeLists.txt */
extern const unsigned char web_index_html[];
extern const unsigned web_index_html_size;
extern const unsigned char web_styles_css[];
extern const unsigned web_styles_css_size;

static const unsigned char http_root_redirect[] =
    "HTTP/1.0 302 Found\r\n"
    "Location: /index.html\r\n"
    "\r\n";

static int http_set_custom_file(struct fs_file *file, const unsigned char *data, unsigned size, u8_t flags)
{
    if ((file == NULL) || (data == NULL))
    {
        return 0;
    }

    file->data = (const char *)data;
    file->len = (int)size;
    file->index = file->len;
    file->pextension = NULL;
    file->flags = flags;

    return 1;
}

int fs_open_custom(struct fs_file *file, const char *name)
{
    if ((file == NULL) || (name == NULL))
    {
        return 0;
    }

    if ((strcmp(name, "/") == 0) || (strcmp(name, "/index.html") == 0))
    {
        if (strcmp(name, "/") == 0)
        {
            return http_set_custom_file(file,
                                        http_root_redirect,
                                        (unsigned)(sizeof(http_root_redirect) - 1U),
                                        FS_FILE_FLAGS_HEADER_INCLUDED | FS_FILE_FLAGS_HEADER_PERSISTENT);
        }

        /* Header is generated at runtime (LWIP_HTTPD_DYNAMIC_HEADERS=1). */
        return http_set_custom_file(file, web_index_html, web_index_html_size, 0U);
    }

    if (strcmp(name, "/styles.css") == 0)
    {
        return http_set_custom_file(file, web_styles_css, web_styles_css_size, 0U);
    }

    return 0;
}

void fs_close_custom(struct fs_file *file)
{
    (void)file;
}
